version: "2"
linters:
  enable:
    - gosec
    - misspell
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G304
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - gosec
          - govet
        path: frontend/node_modules/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
