// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearVariables():Promise<void>;

export function EvaluateAll(arg1:string):Promise<Array<string>>;

export function EvaluateLine(arg1:string):Promise<string>;

export function GetVariables():Promise<Record<string, number>>;

export function LoadPlugins(arg1:Array<string>):Promise<number>;
