// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {calculator} from '../models';

export function ClearHistory():Promise<void>;

export function ClearVariables():Promise<void>;

export function CreateNote():Promise<storage.Note>;

export function DeleteNote(arg1:string):Promise<void>;

export function EvaluateAll(arg1:string):Promise<Array<string>>;

export function EvaluateLine(arg1:string):Promise<string>;

export function ExportNote(arg1:string,arg2:string):Promise<string>;

export function ExportNoteToFile(arg1:string,arg2:string):Promise<string>;

export function GetAllNotes():Promise<Array<storage.Note>>;

export function GetDataDir():Promise<string>;

export function GetDeleteWithoutConfirm():Promise<boolean>;

export function GetHistory():Promise<Array<calculator.HistoryEntry>>;

export function GetNote(arg1:string):Promise<storage.Note>;

export function GetVariables():Promise<Record<string, number>>;

export function ImportNoteFromFile():Promise<storage.Note>;

export function RenameNote(arg1:string,arg2:string):Promise<void>;

export function SaveNoteContent(arg1:string,arg2:string):Promise<void>;

export function SetDeleteWithoutConfirm(arg1:boolean):Promise<void>;
