// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['service']['AppService']['CheckForUpdate']();
}

export function ClearHistory() {
  return window['go']['service']['AppService']['ClearHistory']();
}

export function ClearVariables() {
  return window['go']['service']['AppService']['ClearVariables']();
}

export function CreateNote() {
  return window['go']['service']['AppService']['CreateNote']();
}

export function DeleteNote(arg1) {
  return window['go']['service']['AppService']['DeleteNote'](arg1);
}

export function EvaluateAll(arg1) {
  return window['go']['service']['AppService']['EvaluateAll'](arg1);
}

export function EvaluateGraph(arg1) {
  return window['go']['service']['AppService']['EvaluateGraph'](arg1);
}

export function EvaluateLine(arg1) {
  return window['go']['service']['AppService']['EvaluateLine'](arg1);
}

export function ExportNote(arg1, arg2) {
  return window['go']['service']['AppService']['ExportNote'](arg1, arg2);
}

export function ExportNoteToFile(arg1, arg2) {
  return window['go']['service']['AppService']['ExportNoteToFile'](arg1, arg2);
}

export function GetAllNotes() {
  return window['go']['service']['AppService']['GetAllNotes']();
}

export function GetAppVersion() {
  return window['go']['service']['AppService']['GetAppVersion']();
}

export function GetAutocompleteKeywords() {
  return window['go']['service']['AppService']['GetAutocompleteKeywords']();
}

export function GetCurrencyCacheInfo() {
  return window['go']['service']['AppService']['GetCurrencyCacheInfo']();
}

export function GetDataDir() {
  return window['go']['service']['AppService']['GetDataDir']();
}

export function GetDeleteWithoutConfirm() {
  return window['go']['service']['AppService']['GetDeleteWithoutConfirm']();
}

export function GetDocContent(arg1) {
  return window['go']['service']['AppService']['GetDocContent'](arg1);
}

export function GetDocList() {
  return window['go']['service']['AppService']['GetDocList']();
}

export function GetHistory() {
  return window['go']['service']['AppService']['GetHistory']();
}

export function GetNote(arg1) {
  return window['go']['service']['AppService']['GetNote'](arg1);
}

export function GetPluginThemes() {
  return window['go']['service']['AppService']['GetPluginThemes']();
}

export function GetPlugins() {
  return window['go']['service']['AppService']['GetPlugins']();
}

export function GetPluginsDir() {
  return window['go']['service']['AppService']['GetPluginsDir']();
}

export function GetSettings() {
  return window['go']['service']['AppService']['GetSettings']();
}

export function GetSteps(arg1) {
  return window['go']['service']['AppService']['GetSteps'](arg1);
}

export function GetVariables() {
  return window['go']['service']['AppService']['GetVariables']();
}

export function ImportNoteFromFile() {
  return window['go']['service']['AppService']['ImportNoteFromFile']();
}

export function InitPlugins(arg1) {
  return window['go']['service']['AppService']['InitPlugins'](arg1);
}

export function InstallPlugin(arg1, arg2, arg3) {
  return window['go']['service']['AppService']['InstallPlugin'](arg1, arg2, arg3);
}

export function PerformUpdate() {
  return window['go']['service']['AppService']['PerformUpdate']();
}

export function ReloadPlugins() {
  return window['go']['service']['AppService']['ReloadPlugins']();
}

export function RemovePlugin(arg1, arg2) {
  return window['go']['service']['AppService']['RemovePlugin'](arg1, arg2);
}

export function RenameNote(arg1, arg2) {
  return window['go']['service']['AppService']['RenameNote'](arg1, arg2);
}

export function ReorderNotes(arg1) {
  return window['go']['service']['AppService']['ReorderNotes'](arg1);
}

export function SaveNoteContent(arg1, arg2) {
  return window['go']['service']['AppService']['SaveNoteContent'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['service']['AppService']['SaveSettings'](arg1);
}

export function SetDeleteWithoutConfirm(arg1) {
  return window['go']['service']['AppService']['SetDeleteWithoutConfirm'](arg1);
}

export function SetDocs(arg1) {
  return window['go']['service']['AppService']['SetDocs'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['service']['AppService']['SetPluginEnabled'](arg1, arg2);
}

export function UpdateCurrencyRates() {
  return window['go']['service']['AppService']['UpdateCurrencyRates']();
}
