// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearVariables() {
  return window['go']['service']['AppService']['ClearVariables']();
}

export function EvaluateAll(arg1) {
  return window['go']['service']['AppService']['EvaluateAll'](arg1);
}

export function EvaluateLine(arg1) {
  return window['go']['service']['AppService']['EvaluateLine'](arg1);
}

export function GetVariables() {
  return window['go']['service']['AppService']['GetVariables']();
}

export function LoadPlugins(arg1) {
  return window['go']['service']['AppService']['LoadPlugins'](arg1);
}
