// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {storage} from '../models';
import {calculator} from '../models';
import {plugin} from '../models';

export function CheckForUpdate():Promise<service.UpdateInfo>;

export function ClearHistory():Promise<void>;

export function ClearVariables():Promise<void>;

export function CreateNote():Promise<storage.Note>;

export function DeleteNote(arg1:string):Promise<void>;

export function EvaluateAll(arg1:string):Promise<Array<string>>;

export function EvaluateGraph(arg1:string):Promise<calculator.GraphResult>;

export function EvaluateLine(arg1:string):Promise<string>;

export function ExportNote(arg1:string,arg2:string):Promise<string>;

export function ExportNoteToFile(arg1:string,arg2:string):Promise<string>;

export function GetAllNotes():Promise<Array<storage.Note>>;

export function GetAppVersion():Promise<string>;

export function GetCurrencyCacheInfo():Promise<service.CurrencyCacheInfo>;

export function GetDataDir():Promise<string>;

export function GetDeleteWithoutConfirm():Promise<boolean>;

export function GetDocContent(arg1:string):Promise<string>;

export function GetDocList():Promise<Array<string>>;

export function GetHistory():Promise<Array<calculator.HistoryEntry>>;

export function GetNote(arg1:string):Promise<storage.Note>;

export function GetPluginThemes():Promise<Array<plugin.ThemeDef>>;

export function GetPlugins():Promise<Array<plugin.PluginInfo>>;

export function GetPluginsDir():Promise<string>;

export function GetSettings():Promise<service.SettingsData>;

export function GetSteps(arg1:string):Promise<calculator.EvalDetail>;

export function GetVariables():Promise<Record<string, number>>;

export function ImportNoteFromFile():Promise<storage.Note>;

export function InitPlugins(arg1:string):Promise<void>;

export function InstallPlugin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PerformUpdate():Promise<service.UpdateInfo>;

export function ReloadPlugins():Promise<void>;

export function RemovePlugin(arg1:string,arg2:string):Promise<void>;

export function RenameNote(arg1:string,arg2:string):Promise<void>;

export function ReorderNotes(arg1:Array<string>):Promise<void>;

export function SaveNoteContent(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:service.SettingsData):Promise<void>;

export function SetDeleteWithoutConfirm(arg1:boolean):Promise<void>;

export function SetDocs(arg1:Record<string, string>):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;

export function UpdateCurrencyRates():Promise<service.CurrencyCacheInfo>;
