package storage

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf/v2"
)

func ExportNote(note Note, format string) string {
	switch strings.ToLower(format) {
	case "txt":
		return exportTXT(note)
	case "md":
		return exportMD(note)
	case "json":
		return exportJSON(note)
	case "toml":
		return exportTOML(note)
	case "pdf":
		return exportPDF(note)
	default:
		return exportLV(note)
	}
}

func exportLV(note Note) string {
	return note.Content
}

func exportTXT(note Note) string {
	dt := time.UnixMilli(note.CreatedAt).Format("2006-01-02 15:04:05")
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("Title: %s\n", note.Name))
	buf.WriteString(fmt.Sprintf("Created: %s\n", dt))
	buf.WriteString(fmt.Sprintf("---\n%s\n", note.Content))
	return buf.String()
}

func exportMD(note Note) string {
	dt := time.UnixMilli(note.CreatedAt).Format("2006-01-02 15:04:05")
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("# %s\n\n", note.Name))
	buf.WriteString(fmt.Sprintf("*Created: %s*\n\n", dt))
	buf.WriteString("---\n\n")
	buf.WriteString(note.Content)
	buf.WriteString("\n")
	return buf.String()
}

func exportJSON(note Note) string {
	m := map[string]interface{}{
		"id":        note.ID,
		"name":      note.Name,
		"content":   note.Content,
		"createdAt": note.CreatedAt,
		"updatedAt": note.UpdatedAt,
	}
	b, _ := json.MarshalIndent(m, "", "  ")
	return string(b)
}

func exportTOML(note Note) string {
	dt := time.UnixMilli(note.CreatedAt).Format("2006-01-02T15:04:05-07:00")
	ut := time.UnixMilli(note.UpdatedAt).Format("2006-01-02T15:04:05-07:00")
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("[note]\n"))
	buf.WriteString(fmt.Sprintf("id = %q\n", note.ID))
	buf.WriteString(fmt.Sprintf("name = %q\n", note.Name))
	buf.WriteString(fmt.Sprintf("created_at = %q\n", dt))
	buf.WriteString(fmt.Sprintf("updated_at = %q\n", ut))
	buf.WriteString(fmt.Sprintf("content = %q\n", note.Content))
	return buf.String()
}

func exportPDF(note Note) string {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.SetAutoPageBreak(true, 25)
	pdf.AddPage()

	left, _, _, _ := pdf.GetMargins()
	pageW, _ := pdf.GetPageSize()
	contentW := pageW - left*2

	// Title
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetTextColor(30, 30, 30)
	pdf.Cell(contentW, 14, note.Name)
	pdf.Ln(16)

	// Date line
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(120, 120, 120)
	createdStr := time.UnixMilli(note.CreatedAt).Format("2006-01-02 15:04")
	pdf.Cell(contentW, 5, "Created: "+createdStr)
	if note.UpdatedAt > 0 {
		pdf.Ln(5)
		updatedStr := time.UnixMilli(note.UpdatedAt).Format("2006-01-02 15:04")
		pdf.Cell(contentW, 5, "Updated: "+updatedStr)
	}
	pdf.Ln(10)

	// Separator line
	pdf.SetDrawColor(200, 200, 200)
	pdf.SetLineWidth(0.5)
	y := pdf.GetY()
	pdf.Line(left, y, left+contentW, y)
	pdf.Ln(8)

	// Content
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(50, 50, 50)
	pdf.MultiCell(contentW, 5.5, note.Content, "", "L", false)

	// Footer
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(160, 160, 160)
	_, pageH := pdf.GetPageSize()
	_, _, _, bottom := pdf.GetMargins()
	footerY := pageH - bottom + 3
	for i := 1; i <= pdf.PageCount(); i++ {
		pdf.SetPage(i)
		pdf.SetY(footerY)
		pdf.Cell(contentW, 4, fmt.Sprintf("Generated by LineSolv — Page %d/%d", i, pdf.PageCount()))
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return ""
	}
	return buf.String()
}
